"""Reel / video transcripts as evidence.

Downloads the audio track with yt-dlp (logged-in cookies, never uploaded), keeps
the original audio as its own hashed artefact, sends a compressed copy to the
app for a machine transcript, and saves the verbatim transcript and English
translation as separate hashed text artefacts with a translator statement.

Needs on the Mac mini:  brew install ffmpeg yt-dlp
"""

from __future__ import annotations

import base64
import re
import subprocess
from pathlib import Path
from typing import Any, Callable

from . import api, config
from .live import _tool, _version, _write_cookies

VIDEO_URL = re.compile(r"/(reel|reels|share/r|share/v|videos|watch|video\.php)\b|fb\.watch", re.I)


def is_video_url(url: str) -> bool:
    return bool(VIDEO_URL.search(url or ""))


def capture_transcript(
    context: Any,
    page_url: str,
    job_id: str | None,
    out_dir: Path,
    log: Callable[[str], None],
    record: Callable[[Path, str, str], None],
) -> dict[str, Any] | None:
    try:
        ffmpeg, ytdlp = _tool("ffmpeg"), _tool("yt-dlp")
    except RuntimeError as exc:
        log(f"WARNING: transcript skipped — {exc}")
        return None

    cookie_file = config.WORK_DIR / ".transcript_cookies.txt"  # never evidence
    _write_cookies(context.cookies(), cookie_file)
    try:
        res = subprocess.run(
            [ytdlp, "--cookies", str(cookie_file), "--no-playlist", "-f", "bestaudio/best",
             "-x", "--audio-format", "m4a", "-o", str(out_dir / "reel_audio.%(ext)s"), page_url],
            capture_output=True, text=True, timeout=300,
        )
    finally:
        cookie_file.unlink(missing_ok=True)
    audio = next(iter(sorted(out_dir.glob("reel_audio.*"))), None)
    if res.returncode != 0 or not audio:
        log(f"WARNING: transcript skipped — could not download audio: {(res.stderr or '').strip()[-300:]}")
        return None
    record(audio, "audio_original", "audio/mp4")
    log(f"Saved original audio {audio.name}")

    # Compressed working copy for transcription only (not evidence, not uploaded).
    work = config.WORK_DIR / f".{out_dir.name}_transcribe.mp3"
    subprocess.run([ffmpeg, "-y", "-loglevel", "error", "-i", str(audio), "-ac", "1", "-ar", "16000",
                    "-b:a", "32k", "-t", "3600", str(work)], check=False, timeout=300)
    if not work.exists():
        log("WARNING: transcript skipped — audio conversion failed")
        return None
    try:
        if not job_id:
            raise RuntimeError("no job id")
        result = api.transcribe(job_id, base64.b64encode(work.read_bytes()).decode(), "mp3")
    except Exception as exc:
        log(f"WARNING: transcript failed — {exc}")
        return None
    finally:
        work.unlink(missing_ok=True)

    if not result.get("has_speech", True):
        log("Transcript: no speech detected in the audio")
    statement = (
        f"MACHINE TRANSCRIPT – generated by AI model {result.get('model')} from the audio file "
        f"{audio.name}. Not verified by a human. Must be checked against the original audio by a "
        f"qualified person before use in any report. Tools: {_version(ytdlp, '--version')} (yt-dlp), "
        f"{_version(ffmpeg, '-version')}."
    )
    orig = out_dir / "transcript_original.txt"
    orig.write_text(
        f"{statement}\nSource: {page_url}\nLanguage(s): {result.get('language')}\n\n"
        f"{result.get('transcript_original') or '[no speech]'}\n", encoding="utf-8")
    record(orig, "transcript_original", "text/plain")
    en = out_dir / "transcript_en.txt"
    en.write_text(
        f"{statement}\nTRANSLATION – English translation of transcript_original.txt, machine "
        f"translated, requires human verification.\n\n{result.get('transcript_en') or '[no speech]'}\n",
        encoding="utf-8")
    record(en, "transcript_en", "text/plain")
    log(f"Saved transcript ({result.get('language')}) and English translation")
    return {"language": result.get("language"), "statement": statement,
            "text": result.get("transcript_original"), "text_en": result.get("transcript_en")}
