/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCaptureLogRouteImport } from './routes/_authenticated/capture-log'
import { Route as AuthenticatedCaptureSettingsRouteImport } from './routes/_authenticated/capture-settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedExportRouteImport } from './routes/_authenticated/export'
import { Route as AuthenticatedOfflineRouteImport } from './routes/_authenticated/offline'
import { Route as AuthenticatedQueueRouteImport } from './routes/_authenticated/queue'
import { Route as AuthenticatedResultsRouteImport } from './routes/_authenticated/results'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedVerifyRouteImport } from './routes/_authenticated/verify'
import { Route as AuthenticatedWorkerRouteImport } from './routes/_authenticated/worker'
import { Route as AuthenticatedCasesIndexRouteImport } from './routes/_authenticated/cases.index'
import { Route as AuthenticatedCasesCaseIdRouteImport } from './routes/_authenticated/cases.$caseId'
import { Route as AuthenticatedCommentsCaseIdRouteImport } from './routes/_authenticated/comments.$caseId'
import { Route as AuthenticatedItemsItemIdRouteImport } from './routes/_authenticated/items.$itemId'
import { Route as AuthenticatedJobsJobIdRouteImport } from './routes/_authenticated/jobs.$jobId'
import { Route as AuthenticatedProfilesCaseIdRouteImport } from './routes/_authenticated/profiles.$caseId'
import { Route as AuthenticatedReportCaseIdRouteImport } from './routes/_authenticated/report.$caseId'
import { Route as AuthenticatedReviewCaseIdRouteImport } from './routes/_authenticated/review.$caseId'
import { Route as AuthenticatedSummaryCaseIdRouteImport } from './routes/_authenticated/summary.$caseId'
import { Route as AuthenticatedTrailCaseIdRouteImport } from './routes/_authenticated/trail.$caseId'
import { Route as AuthenticatedTranscriptsCaseIdRouteImport } from './routes/_authenticated/transcripts.$caseId'
import { Route as ApiPublicWorkerClaimRouteImport } from './routes/api/public/worker-claim'
import { Route as ApiPublicWorkerCompleteRouteImport } from './routes/api/public/worker-complete'
import { Route as ApiPublicWorkerHeartbeatRouteImport } from './routes/api/public/worker-heartbeat'
import { Route as ApiPublicWorkerIngestRouteImport } from './routes/api/public/worker-ingest'
import { Route as ApiPublicWorkerLogRouteImport } from './routes/api/public/worker-log'
import { Route as ApiPublicWorkerTranscribeRouteImport } from './routes/api/public/worker-transcribe'
import { Route as ApiPublicWorkerUploadUrlRouteImport } from './routes/api/public/worker-upload-url'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCaptureLogRoute = AuthenticatedCaptureLogRouteImport.update({
  id: '/capture-log',
  path: '/capture-log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCaptureSettingsRoute =
  AuthenticatedCaptureSettingsRouteImport.update({
    id: '/capture-settings',
    path: '/capture-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExportRoute = AuthenticatedExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOfflineRoute = AuthenticatedOfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQueueRoute = AuthenticatedQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResultsRoute = AuthenticatedResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVerifyRoute = AuthenticatedVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkerRoute = AuthenticatedWorkerRouteImport.update({
  id: '/worker',
  path: '/worker',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCasesIndexRoute = AuthenticatedCasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCasesCaseIdRoute =
  AuthenticatedCasesCaseIdRouteImport.update({
    id: '/cases/$caseId',
    path: '/cases/$caseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommentsCaseIdRoute =
  AuthenticatedCommentsCaseIdRouteImport.update({
    id: '/comments/$caseId',
    path: '/comments/$caseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedItemsItemIdRoute =
  AuthenticatedItemsItemIdRouteImport.update({
    id: '/items/$itemId',
    path: '/items/$itemId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJobsJobIdRoute = AuthenticatedJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilesCaseIdRoute =
  AuthenticatedProfilesCaseIdRouteImport.update({
    id: '/profiles/$caseId',
    path: '/profiles/$caseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportCaseIdRoute =
  AuthenticatedReportCaseIdRouteImport.update({
    id: '/report/$caseId',
    path: '/report/$caseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReviewCaseIdRoute =
  AuthenticatedReviewCaseIdRouteImport.update({
    id: '/review/$caseId',
    path: '/review/$caseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSummaryCaseIdRoute =
  AuthenticatedSummaryCaseIdRouteImport.update({
    id: '/summary/$caseId',
    path: '/summary/$caseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrailCaseIdRoute =
  AuthenticatedTrailCaseIdRouteImport.update({
    id: '/trail/$caseId',
    path: '/trail/$caseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTranscriptsCaseIdRoute =
  AuthenticatedTranscriptsCaseIdRouteImport.update({
    id: '/transcripts/$caseId',
    path: '/transcripts/$caseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicWorkerClaimRoute = ApiPublicWorkerClaimRouteImport.update({
  id: '/api/public/worker-claim',
  path: '/api/public/worker-claim',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkerCompleteRoute = ApiPublicWorkerCompleteRouteImport.update({
  id: '/api/public/worker-complete',
  path: '/api/public/worker-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkerHeartbeatRoute =
  ApiPublicWorkerHeartbeatRouteImport.update({
    id: '/api/public/worker-heartbeat',
    path: '/api/public/worker-heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWorkerIngestRoute = ApiPublicWorkerIngestRouteImport.update({
  id: '/api/public/worker-ingest',
  path: '/api/public/worker-ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkerLogRoute = ApiPublicWorkerLogRouteImport.update({
  id: '/api/public/worker-log',
  path: '/api/public/worker-log',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkerTranscribeRoute =
  ApiPublicWorkerTranscribeRouteImport.update({
    id: '/api/public/worker-transcribe',
    path: '/api/public/worker-transcribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWorkerUploadUrlRoute =
  ApiPublicWorkerUploadUrlRouteImport.update({
    id: '/api/public/worker-upload-url',
    path: '/api/public/worker-upload-url',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/capture-log': typeof AuthenticatedCaptureLogRoute
  '/capture-settings': typeof AuthenticatedCaptureSettingsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/export': typeof AuthenticatedExportRoute
  '/offline': typeof AuthenticatedOfflineRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/results': typeof AuthenticatedResultsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/verify': typeof AuthenticatedVerifyRoute
  '/worker': typeof AuthenticatedWorkerRoute
  '/cases/$caseId': typeof AuthenticatedCasesCaseIdRoute
  '/comments/$caseId': typeof AuthenticatedCommentsCaseIdRoute
  '/items/$itemId': typeof AuthenticatedItemsItemIdRoute
  '/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/profiles/$caseId': typeof AuthenticatedProfilesCaseIdRoute
  '/report/$caseId': typeof AuthenticatedReportCaseIdRoute
  '/review/$caseId': typeof AuthenticatedReviewCaseIdRoute
  '/summary/$caseId': typeof AuthenticatedSummaryCaseIdRoute
  '/trail/$caseId': typeof AuthenticatedTrailCaseIdRoute
  '/transcripts/$caseId': typeof AuthenticatedTranscriptsCaseIdRoute
  '/api/public/worker-claim': typeof ApiPublicWorkerClaimRoute
  '/api/public/worker-complete': typeof ApiPublicWorkerCompleteRoute
  '/api/public/worker-heartbeat': typeof ApiPublicWorkerHeartbeatRoute
  '/api/public/worker-ingest': typeof ApiPublicWorkerIngestRoute
  '/api/public/worker-log': typeof ApiPublicWorkerLogRoute
  '/api/public/worker-transcribe': typeof ApiPublicWorkerTranscribeRoute
  '/api/public/worker-upload-url': typeof ApiPublicWorkerUploadUrlRoute
  '/cases/': typeof AuthenticatedCasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/capture-log': typeof AuthenticatedCaptureLogRoute
  '/capture-settings': typeof AuthenticatedCaptureSettingsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/export': typeof AuthenticatedExportRoute
  '/offline': typeof AuthenticatedOfflineRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/results': typeof AuthenticatedResultsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/verify': typeof AuthenticatedVerifyRoute
  '/worker': typeof AuthenticatedWorkerRoute
  '/cases/$caseId': typeof AuthenticatedCasesCaseIdRoute
  '/comments/$caseId': typeof AuthenticatedCommentsCaseIdRoute
  '/items/$itemId': typeof AuthenticatedItemsItemIdRoute
  '/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/profiles/$caseId': typeof AuthenticatedProfilesCaseIdRoute
  '/report/$caseId': typeof AuthenticatedReportCaseIdRoute
  '/review/$caseId': typeof AuthenticatedReviewCaseIdRoute
  '/summary/$caseId': typeof AuthenticatedSummaryCaseIdRoute
  '/trail/$caseId': typeof AuthenticatedTrailCaseIdRoute
  '/transcripts/$caseId': typeof AuthenticatedTranscriptsCaseIdRoute
  '/api/public/worker-claim': typeof ApiPublicWorkerClaimRoute
  '/api/public/worker-complete': typeof ApiPublicWorkerCompleteRoute
  '/api/public/worker-heartbeat': typeof ApiPublicWorkerHeartbeatRoute
  '/api/public/worker-ingest': typeof ApiPublicWorkerIngestRoute
  '/api/public/worker-log': typeof ApiPublicWorkerLogRoute
  '/api/public/worker-transcribe': typeof ApiPublicWorkerTranscribeRoute
  '/api/public/worker-upload-url': typeof ApiPublicWorkerUploadUrlRoute
  '/cases': typeof AuthenticatedCasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/capture-log': typeof AuthenticatedCaptureLogRoute
  '/_authenticated/capture-settings': typeof AuthenticatedCaptureSettingsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/export': typeof AuthenticatedExportRoute
  '/_authenticated/offline': typeof AuthenticatedOfflineRoute
  '/_authenticated/queue': typeof AuthenticatedQueueRoute
  '/_authenticated/results': typeof AuthenticatedResultsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/verify': typeof AuthenticatedVerifyRoute
  '/_authenticated/worker': typeof AuthenticatedWorkerRoute
  '/_authenticated/cases/$caseId': typeof AuthenticatedCasesCaseIdRoute
  '/_authenticated/comments/$caseId': typeof AuthenticatedCommentsCaseIdRoute
  '/_authenticated/items/$itemId': typeof AuthenticatedItemsItemIdRoute
  '/_authenticated/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/_authenticated/profiles/$caseId': typeof AuthenticatedProfilesCaseIdRoute
  '/_authenticated/report/$caseId': typeof AuthenticatedReportCaseIdRoute
  '/_authenticated/review/$caseId': typeof AuthenticatedReviewCaseIdRoute
  '/_authenticated/summary/$caseId': typeof AuthenticatedSummaryCaseIdRoute
  '/_authenticated/trail/$caseId': typeof AuthenticatedTrailCaseIdRoute
  '/_authenticated/transcripts/$caseId': typeof AuthenticatedTranscriptsCaseIdRoute
  '/api/public/worker-claim': typeof ApiPublicWorkerClaimRoute
  '/api/public/worker-complete': typeof ApiPublicWorkerCompleteRoute
  '/api/public/worker-heartbeat': typeof ApiPublicWorkerHeartbeatRoute
  '/api/public/worker-ingest': typeof ApiPublicWorkerIngestRoute
  '/api/public/worker-log': typeof ApiPublicWorkerLogRoute
  '/api/public/worker-transcribe': typeof ApiPublicWorkerTranscribeRoute
  '/api/public/worker-upload-url': typeof ApiPublicWorkerUploadUrlRoute
  '/_authenticated/cases/': typeof AuthenticatedCasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/capture-log'
    | '/capture-settings'
    | '/dashboard'
    | '/export'
    | '/offline'
    | '/queue'
    | '/results'
    | '/settings'
    | '/team'
    | '/templates'
    | '/verify'
    | '/worker'
    | '/cases/$caseId'
    | '/comments/$caseId'
    | '/items/$itemId'
    | '/jobs/$jobId'
    | '/profiles/$caseId'
    | '/report/$caseId'
    | '/review/$caseId'
    | '/summary/$caseId'
    | '/trail/$caseId'
    | '/transcripts/$caseId'
    | '/api/public/worker-claim'
    | '/api/public/worker-complete'
    | '/api/public/worker-heartbeat'
    | '/api/public/worker-ingest'
    | '/api/public/worker-log'
    | '/api/public/worker-transcribe'
    | '/api/public/worker-upload-url'
    | '/cases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/capture-log'
    | '/capture-settings'
    | '/dashboard'
    | '/export'
    | '/offline'
    | '/queue'
    | '/results'
    | '/settings'
    | '/team'
    | '/templates'
    | '/verify'
    | '/worker'
    | '/cases/$caseId'
    | '/comments/$caseId'
    | '/items/$itemId'
    | '/jobs/$jobId'
    | '/profiles/$caseId'
    | '/report/$caseId'
    | '/review/$caseId'
    | '/summary/$caseId'
    | '/trail/$caseId'
    | '/transcripts/$caseId'
    | '/api/public/worker-claim'
    | '/api/public/worker-complete'
    | '/api/public/worker-heartbeat'
    | '/api/public/worker-ingest'
    | '/api/public/worker-log'
    | '/api/public/worker-transcribe'
    | '/api/public/worker-upload-url'
    | '/cases'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/capture-log'
    | '/_authenticated/capture-settings'
    | '/_authenticated/dashboard'
    | '/_authenticated/export'
    | '/_authenticated/offline'
    | '/_authenticated/queue'
    | '/_authenticated/results'
    | '/_authenticated/settings'
    | '/_authenticated/team'
    | '/_authenticated/templates'
    | '/_authenticated/verify'
    | '/_authenticated/worker'
    | '/_authenticated/cases/$caseId'
    | '/_authenticated/comments/$caseId'
    | '/_authenticated/items/$itemId'
    | '/_authenticated/jobs/$jobId'
    | '/_authenticated/profiles/$caseId'
    | '/_authenticated/report/$caseId'
    | '/_authenticated/review/$caseId'
    | '/_authenticated/summary/$caseId'
    | '/_authenticated/trail/$caseId'
    | '/_authenticated/transcripts/$caseId'
    | '/api/public/worker-claim'
    | '/api/public/worker-complete'
    | '/api/public/worker-heartbeat'
    | '/api/public/worker-ingest'
    | '/api/public/worker-log'
    | '/api/public/worker-transcribe'
    | '/api/public/worker-upload-url'
    | '/_authenticated/cases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicWorkerClaimRoute: typeof ApiPublicWorkerClaimRoute
  ApiPublicWorkerCompleteRoute: typeof ApiPublicWorkerCompleteRoute
  ApiPublicWorkerHeartbeatRoute: typeof ApiPublicWorkerHeartbeatRoute
  ApiPublicWorkerIngestRoute: typeof ApiPublicWorkerIngestRoute
  ApiPublicWorkerLogRoute: typeof ApiPublicWorkerLogRoute
  ApiPublicWorkerTranscribeRoute: typeof ApiPublicWorkerTranscribeRoute
  ApiPublicWorkerUploadUrlRoute: typeof ApiPublicWorkerUploadUrlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/capture-log': {
      id: '/_authenticated/capture-log'
      path: '/capture-log'
      fullPath: '/capture-log'
      preLoaderRoute: typeof AuthenticatedCaptureLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/capture-settings': {
      id: '/_authenticated/capture-settings'
      path: '/capture-settings'
      fullPath: '/capture-settings'
      preLoaderRoute: typeof AuthenticatedCaptureSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/export': {
      id: '/_authenticated/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AuthenticatedExportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offline': {
      id: '/_authenticated/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof AuthenticatedOfflineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/queue': {
      id: '/_authenticated/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof AuthenticatedQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/results': {
      id: '/_authenticated/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AuthenticatedResultsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/verify': {
      id: '/_authenticated/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthenticatedVerifyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/worker': {
      id: '/_authenticated/worker'
      path: '/worker'
      fullPath: '/worker'
      preLoaderRoute: typeof AuthenticatedWorkerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cases/': {
      id: '/_authenticated/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof AuthenticatedCasesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cases/$caseId': {
      id: '/_authenticated/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof AuthenticatedCasesCaseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comments/$caseId': {
      id: '/_authenticated/comments/$caseId'
      path: '/comments/$caseId'
      fullPath: '/comments/$caseId'
      preLoaderRoute: typeof AuthenticatedCommentsCaseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/items/$itemId': {
      id: '/_authenticated/items/$itemId'
      path: '/items/$itemId'
      fullPath: '/items/$itemId'
      preLoaderRoute: typeof AuthenticatedItemsItemIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/$jobId': {
      id: '/_authenticated/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof AuthenticatedJobsJobIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profiles/$caseId': {
      id: '/_authenticated/profiles/$caseId'
      path: '/profiles/$caseId'
      fullPath: '/profiles/$caseId'
      preLoaderRoute: typeof AuthenticatedProfilesCaseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report/$caseId': {
      id: '/_authenticated/report/$caseId'
      path: '/report/$caseId'
      fullPath: '/report/$caseId'
      preLoaderRoute: typeof AuthenticatedReportCaseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/review/$caseId': {
      id: '/_authenticated/review/$caseId'
      path: '/review/$caseId'
      fullPath: '/review/$caseId'
      preLoaderRoute: typeof AuthenticatedReviewCaseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/summary/$caseId': {
      id: '/_authenticated/summary/$caseId'
      path: '/summary/$caseId'
      fullPath: '/summary/$caseId'
      preLoaderRoute: typeof AuthenticatedSummaryCaseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trail/$caseId': {
      id: '/_authenticated/trail/$caseId'
      path: '/trail/$caseId'
      fullPath: '/trail/$caseId'
      preLoaderRoute: typeof AuthenticatedTrailCaseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transcripts/$caseId': {
      id: '/_authenticated/transcripts/$caseId'
      path: '/transcripts/$caseId'
      fullPath: '/transcripts/$caseId'
      preLoaderRoute: typeof AuthenticatedTranscriptsCaseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/worker-claim': {
      id: '/api/public/worker-claim'
      path: '/api/public/worker-claim'
      fullPath: '/api/public/worker-claim'
      preLoaderRoute: typeof ApiPublicWorkerClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker-complete': {
      id: '/api/public/worker-complete'
      path: '/api/public/worker-complete'
      fullPath: '/api/public/worker-complete'
      preLoaderRoute: typeof ApiPublicWorkerCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker-heartbeat': {
      id: '/api/public/worker-heartbeat'
      path: '/api/public/worker-heartbeat'
      fullPath: '/api/public/worker-heartbeat'
      preLoaderRoute: typeof ApiPublicWorkerHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker-ingest': {
      id: '/api/public/worker-ingest'
      path: '/api/public/worker-ingest'
      fullPath: '/api/public/worker-ingest'
      preLoaderRoute: typeof ApiPublicWorkerIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker-log': {
      id: '/api/public/worker-log'
      path: '/api/public/worker-log'
      fullPath: '/api/public/worker-log'
      preLoaderRoute: typeof ApiPublicWorkerLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker-transcribe': {
      id: '/api/public/worker-transcribe'
      path: '/api/public/worker-transcribe'
      fullPath: '/api/public/worker-transcribe'
      preLoaderRoute: typeof ApiPublicWorkerTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker-upload-url': {
      id: '/api/public/worker-upload-url'
      path: '/api/public/worker-upload-url'
      fullPath: '/api/public/worker-upload-url'
      preLoaderRoute: typeof ApiPublicWorkerUploadUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCaptureLogRoute: typeof AuthenticatedCaptureLogRoute
  AuthenticatedCaptureSettingsRoute: typeof AuthenticatedCaptureSettingsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExportRoute: typeof AuthenticatedExportRoute
  AuthenticatedOfflineRoute: typeof AuthenticatedOfflineRoute
  AuthenticatedQueueRoute: typeof AuthenticatedQueueRoute
  AuthenticatedResultsRoute: typeof AuthenticatedResultsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedVerifyRoute: typeof AuthenticatedVerifyRoute
  AuthenticatedWorkerRoute: typeof AuthenticatedWorkerRoute
  AuthenticatedCasesCaseIdRoute: typeof AuthenticatedCasesCaseIdRoute
  AuthenticatedCommentsCaseIdRoute: typeof AuthenticatedCommentsCaseIdRoute
  AuthenticatedItemsItemIdRoute: typeof AuthenticatedItemsItemIdRoute
  AuthenticatedJobsJobIdRoute: typeof AuthenticatedJobsJobIdRoute
  AuthenticatedProfilesCaseIdRoute: typeof AuthenticatedProfilesCaseIdRoute
  AuthenticatedReportCaseIdRoute: typeof AuthenticatedReportCaseIdRoute
  AuthenticatedReviewCaseIdRoute: typeof AuthenticatedReviewCaseIdRoute
  AuthenticatedSummaryCaseIdRoute: typeof AuthenticatedSummaryCaseIdRoute
  AuthenticatedTrailCaseIdRoute: typeof AuthenticatedTrailCaseIdRoute
  AuthenticatedTranscriptsCaseIdRoute: typeof AuthenticatedTranscriptsCaseIdRoute
  AuthenticatedCasesIndexRoute: typeof AuthenticatedCasesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCaptureLogRoute: AuthenticatedCaptureLogRoute,
  AuthenticatedCaptureSettingsRoute: AuthenticatedCaptureSettingsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExportRoute: AuthenticatedExportRoute,
  AuthenticatedOfflineRoute: AuthenticatedOfflineRoute,
  AuthenticatedQueueRoute: AuthenticatedQueueRoute,
  AuthenticatedResultsRoute: AuthenticatedResultsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedVerifyRoute: AuthenticatedVerifyRoute,
  AuthenticatedWorkerRoute: AuthenticatedWorkerRoute,
  AuthenticatedCasesCaseIdRoute: AuthenticatedCasesCaseIdRoute,
  AuthenticatedCommentsCaseIdRoute: AuthenticatedCommentsCaseIdRoute,
  AuthenticatedItemsItemIdRoute: AuthenticatedItemsItemIdRoute,
  AuthenticatedJobsJobIdRoute: AuthenticatedJobsJobIdRoute,
  AuthenticatedProfilesCaseIdRoute: AuthenticatedProfilesCaseIdRoute,
  AuthenticatedReportCaseIdRoute: AuthenticatedReportCaseIdRoute,
  AuthenticatedReviewCaseIdRoute: AuthenticatedReviewCaseIdRoute,
  AuthenticatedSummaryCaseIdRoute: AuthenticatedSummaryCaseIdRoute,
  AuthenticatedTrailCaseIdRoute: AuthenticatedTrailCaseIdRoute,
  AuthenticatedTranscriptsCaseIdRoute: AuthenticatedTranscriptsCaseIdRoute,
  AuthenticatedCasesIndexRoute: AuthenticatedCasesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicWorkerClaimRoute: ApiPublicWorkerClaimRoute,
  ApiPublicWorkerCompleteRoute: ApiPublicWorkerCompleteRoute,
  ApiPublicWorkerHeartbeatRoute: ApiPublicWorkerHeartbeatRoute,
  ApiPublicWorkerIngestRoute: ApiPublicWorkerIngestRoute,
  ApiPublicWorkerLogRoute: ApiPublicWorkerLogRoute,
  ApiPublicWorkerTranscribeRoute: ApiPublicWorkerTranscribeRoute,
  ApiPublicWorkerUploadUrlRoute: ApiPublicWorkerUploadUrlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
